### ISSUE TITLE
president_speech 데이터셋에 contents 변수가 없습니다.

### ISSUE THREAD

**Issue by sens5900r** [bit2r/bitTA#19]
president_speech$contents[1:100] %>% 
  morpho_mecab(indiv = FALSE) %>% 
  table() %>% 
  wordcloud2::wordcloud2(fontFamily = "NanumSquare")

예제가 작동하지 않습니다.  contents를 doc로 바꾸어 실행하였습니다. 작동합니다.

president_speech$doc[1:100] %>% 
  morpho_mecab(indiv = FALSE) %>% 
  table() %>% 
  wordcloud2::wordcloud2(fontFamily = "NanumSquare")

**Comment by choonghyunryu** [comment]
@sens5900r,

수정해서 올려 놓았습니다.
