### ISSUE TITLE
README.Rmd tidytext와의 협업 윈도우즈 오류

### ISSUE THREAD

**Issue by statkclee** [bit2r/bitTA#22]
병렬처리관련 패키지가 맥 기준으로 되어 있어 윈도우에서 실행할 경우 오류가 나는 것으로 보입니다.

### tidytext와의 협업

`tidytext` 패키지와의 협업을 위한 기능은 비네트인 [Collaboration with tidytext package](https://r2bit.com/bitTA/articles/with_tidytext.html){target='_blank'}에 설명되어 있습니다. 

#### tokenizers

bitTA는 토크나이저로 다음과 같은 함수를 지원합니다.

* 형태소 토크나이저
  - morpho_mecab()
  - part-of-speech tagger 단위의 토크나이저
* 명사 n-grams 토크나이저
  - **tokenize_noun_ngrams()**

```
> # simplify = TRUE
> tokenize_noun_ngrams(docs[1], simplify = TRUE)
Error in parallel::mclapply(seq(chunk_idx$idx_start), get_collapse_noun,  : 
  'mc.cores' > 1 is not supported on Windows
Backtrace:
 1. bitTA::tokenize_noun_ngrams(docs[1], simplify = TRUE)
 2. bitTA::collapse_noun(x, type = type, user_dic = user_dic)
 3. parallel::mclapply(...)
```

**Comment by choonghyunryu** [comment]
@statkclee,
문제를 확인 후 fix하겠습니다.

**Comment by choonghyunryu** [comment]
@statkclee,
수정 완료하였습니다.

tokenize_noun_ngrams(), collapse_noun() 함수는 MS-Windows에서 병렬처리를 지원하지 못합니다.
이 예외처리에 오류가 있어서 MS-Windows는 Sequence처리하도록 수정했습니다.
