### ISSUE TITLE
bitTA::explore_docs() Shiny ngram 오류

### ISSUE THREAD

**Issue by statkclee** [bit2r/bitTA#23]
bitTA::explore_docs() 함수에서 호출하는 Shiny server.R 함수명이 get_ngrams() 여야 되는데 get_ngram() 으로 되어 있습니다. 이를 수정해도 
다음 오류가 발생됩니다. 

```
경고: Error in is.string: 객체 'ngram_delim'를 찾을 수 없습니다
  2: runApp
  1: bitTA::explore_docs [/Users/tidyverse/swc/bitTA/R/shiny.R#20]
```

**Comment by choonghyunryu** [comment]
@statkclee,

버그수정해서 1.3.0.9007 버전으로 판올림했습니다.
get_ngrams()에서 발생하는 에러였습니다.
