### ISSUE TITLE
Mecab for Windows 가 64bit 가 아니면 치명적인 오류가 발생하네요...

### ISSUE THREAD

**Issue by statkclee** [bit2r/bitTA#5]
RMeCab의 64 bit 버전이 설치되지 않은 듯... 이런 경우 치명적인 오류가 발생합니다.

[오류 스크린샷](https://imgur.com/a/hJRh32K)

**Comment by euriion** [comment]
Mecab의 일본어 버전과 한국의 은전한닢(MecabKo)는 다른데 일본어만 있는 몇가지 처리를 제거하고 한국어만 필요한 코드를 추가한  한국어버전이기 때문에 한국어, 일본어 버전의 코어 모듈이 동일하지 않습니다.  수년전 일본 와세다 대학의 텍스트마이닝 박사과정생들에게 확인받은 사항입니다. 그래서 코어모듈과 데이터의 쌍을 잘 맞춰야하는 문제가 있습니다.
Mecab의 Windows 버전은 64bit 버전이 제대로 작동안하는 고질적인 문제가 예전부터 있었습니다. 32비트 버전을 사용해야 할 수 있습니다.
Mecab 빌드가 Windows에서 하기에는 작업시간이 많이 걸리고 조금 까다로운 경향이 있습니다.

**Comment by choonghyunryu** [comment]
README에 Windows/Linux에서 Mecab과 사전을 설치하는 방법을 정리해 놓겠습니다.
Windows에서는 컴파일된 msvc 버전이 있더군요.
Windows가 싫지만, 다수가 사용하는 환경이라 어쩔 수 없군요.

**Comment by choonghyunryu** [comment]
먼저 맥과 리눅스는 mecab-ko와 mecab-ko-dic을 설치하는 함수를 만들면 될 것 같습니다.
RStudio에서 만든 tensorflow 패키지가 install_tensorflow() 함수로 tensorflow를 설치하는 것 처럼
install_mecab-ko() 함수를 만들어 보겠습니다.

**Comment by choonghyunryu** [comment]
install_mecab_ko() 함수를 추가했습니다. 
Linux, Mac 환경에서 mecab-ko와 mecab-ko-dic을 설치합니다.
MS-Windows는 아직 미구현입니다. 좀 더 최선의 솔루션을 찾아봐야합니다.
Linux, Mac 환경의 테스트 부탁합니다.

**Comment by choonghyunryu** [comment]
### 해당 이슈 해결
* Windows: RmecabKo(https://github.com/junhewk/RmecabKo) 패키지에 mecab-ko-mvc 바이너리를 설치하는 로직이 있어
이 로직을 이식함
* Linux/Mac: 자체 설치 스크립트를 만들었음
